diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.editor="C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=harishbehera123
user.email=beheraharish950@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/shivabaipalli/sample-project.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.main.vscode-merge-base=origin/main
branch.main.vscode-merge-base=origin/main
branch.hb-domy.vscode-merge-base=origin/main
branch.hb-domy.remote=origin
branch.hb-domy.merge=refs/heads/hb-domy
branch.hb-domy.github-pr-owner-number=shivabaipalli#sample-project#1
branch.hb-domy.github-pr-owner-number=shivabaipalli#sample-project#1
branch.hb-domy.github-pr-owner-number=shivabaipalli#sample-project#1
